# Generated by Django 4.1.1 on 2023-08-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='avaliability',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
