# Generated by Django 4.1.1 on 2023-08-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_subcategory_avaliability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='avaliability',
            new_name='availability',
        ),
    ]
