# Generated by Django 4.2.3 on 2023-08-05 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_avaliability_subcategory_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=24, unique=True)),
                ('product_name', models.CharField(max_length=264)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('gst', models.FloatField(null=True)),
                ('available', models.BooleanField(default=True)),
                ('min_level', models.IntegerField(null=True)),
                ('delivery_within', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.subcategory')),
            ],
        ),
    ]
