# Generated by Django 4.1.1 on 2023-08-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=264)),
                ('size', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
