# Generated by Django 4.1.1 on 2023-08-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_ratings_dress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('top_speed', models.IntegerField()),
                ('fuel', models.CharField(max_length=50)),
                ('engine_cc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=50)),
                ('launched_year', models.IntegerField()),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.details')),
            ],
        ),
    ]
